[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "python310Packages.setuptools",
  "python310Packages.wheel"
]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install python-docx requests openai ffmpeg-python",
  "python -m pip install -U openai-whisper",
  "echo 'Python y dependencias instaladas correctamente'"
]

[start]
cmd = "node server.js"