[phases.setup]
nixPkgs = [
  "python39",
  "python39Packages.pip",
  "ffmpeg"
]

[phases.install]
cmds = [
  "cd backend",
  "npm install",
  "pip install SpeechRecognition pydub python-docx requests"
]

[start]
cmd = "cd backend && node server.js"