[phases.setup]
nixPkgs = [
  "python39",
  "python39Packages.pip",
  "python39Packages.setuptools",
  "python39Packages.wheel",
  "ffmpeg",
  "gcc"
]

[phases.install]
aptPkgs = [
  "portaudio19-dev",
  "libpython3-dev",
  "python3-pyaudio"
]
cmds = [
  "cd backend",
  "npm install",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install SpeechRecognition pydub python-docx requests pyaudio",
  "python3 -c 'import speech_recognition; print(\"SpeechRecognition instalado correctamente\")'"
]

[start]
cmd = "cd backend && node server.js"